# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..2
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: "GwangseongCho"
tagline: ""
description: ""
url: http://gwangseongcho.github.io

author:
  name: GwangseongCho"

paginate: 5

# Custom vars
#version: 2.1.0

github:
  repo: https://github.com/poole/hyde
