# Dependencies

markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..2
  # parse_block_html: true

# markdown: CommonMarkGhPages

highlighter: rouge

# Permalinks
# permalink:        pretty

# Setup
title: "Seong's Notes"
tagline: ""
description: ""
url: https://gwangseongcho.github.io
baseurl: https://gwangseongcho.github.io

author:
  name: "Gwangseong Cho"

paginate: 10

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/gwangseongcho/gwangseongcho.github.io

plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages

disqus:
  shortname: gwangseongcho
